services:
  purchase:
    image: mysql:8.0
    container_name: purchase_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: purchase
    ports:
      - "5433:3306"
    volumes:
      - purchase_data:/var/lib/mysql
    networks:
      - purchase-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=mysql://root@db:3306/purchase
      - PORT=3000
      - FRONTEND_URL=http://localhost
    ports:
      - "3000:3000"
    depends_on:
      - purchase
    networks:
      - purchase-network

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   environment:
  #     - VITE_API_URL=http://localhost:3000
  #     - VITE_SOCKET_URL=http://localhost:3000
  #   networks:
  #     - chat-network

volumes:
  purchase_data:

networks:
  purchase-network:
    driver: bridge
