services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - chat-network

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - chat-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/chatdb?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
      - FRONTEND_URL=http://localhost
      - JWT_SECRET=your-super-secret-jwt-key
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    networks:
      - chat-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3000
      - VITE_SOCKET_URL=http://localhost:3000
    networks:
      - chat-network

volumes:
  db_data:

networks:
  chat-network:
    driver: bridge